sudo: required
services:
  - docker

before_install:
  - docker build -t thcrnk/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run thcrnk/react-test npm test -- --coverage

after_success:
  - docker build -t thcrnk/multi-client ./client
  - docker build -t thcrnk/multi-nginx ./nginx
  - docker build -t thcrnk/multi-server ./server
  - docker build -t thcrnk/multi-worker ./worker
  # Login to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push to docker hub
  - docker push thcrnk/multi-client
  - docker push thcrnk/multi-nginx
  - docker push thcrnk/multi-server
  - docker push thcrnk/multi-worker