sudo: required
services:
  - docker

before_install:
  - docker build -t thcrnk/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run thcrnk/react-test npm test -- --coverage

after_success:
  - docker build -t thcrnk/multi-client ./client
  - docker build -t thcrnk/multi-nginx ./nginx
  - docker build -t thcrnk/multi-server ./server
  - docker build -t thcrnk/multi-worker ./worker
  # Login to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push to docker hub
  - docker push thcrnk/multi-client
  - docker push thcrnk/multi-nginx
  - docker push thcrnk/multi-server
  - docker push thcrnk/multi-worker

deploy:
  provider: elasticbeanstalk,
  region: us-west-1,
  app: multi-docker,
  env: Multi-docker-env,
  bucket_name: s3 bucket name,
  bucket_path: docker-mulit,
  on:
    branch: master,
  access_key_id: $AWS_ACCESS_KEY,
  secret_access_key:
    secure: $AWS_SECRET_KEY